### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by clemensv** [duglin/xreg-github#2]
Could you add a GH action to wrap the latest into a Docker image and publish it here on GH? I'd like to pull that container for API tests then.

I have a workflow that I run for my "real-time-sources" repo that has all the required steps.

https://github.com/clemensv/real-time-sources/blob/main/.github/workflows/build_containers.yml

(Docs: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images, https://github.com/sigstore/cosign-installer)

The only "magic" in that workflow is that I collect several dockerfiles and run a matrix for them. My published images end up here:

https://github.com/clemensv?tab=packages&repo_name=real-time-sources

**Comment by duglin** [comment]
Until I set it up you can download it from dockerhub: duglin/xreg-server (for just the server) and duglin/xreg-server-all (for the server+mysql). You probably want the "all" one.

**Comment by clemensv** [comment]
Very nice. Thank you.

**Comment by duglin** [comment]
Done, you can see the images here: https://github.com/duglin?tab=packages
